// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExistenceChecker is an autogenerated mock type for the ExistenceChecker type
type ExistenceChecker struct {
	mock.Mock
}

// CheckExistence provides a mock function with given fields: id
func (_m *ExistenceChecker) CheckExistence(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
