openapi: 3.0.1
info:
  description: "This is a hotel management API."
  version: "1.0.0"
  title: "Hotel management API"
  contact:
    email: "dimad_1996@mail.ru"
basePath: "/"
tags:
  - name: "rooms"
  #    description: "Everything about your Pets"
  - name: "bookings"
#    description: "Access to Petstore orders"
schemes:
  - "http"
paths:
  /rooms:
    get:
      tags:
        - "rooms"
      summary: "Return room list"
      description: ""
      operationId: "getRooms"
      produces:
        - "application/json"
      parameters:
        - name: "sort_by"
          in: "path"
          description: "sort"
          required: false
          schema:
            type: string
            enum:
              - price
              - date_added
        - name: "order_by"
          in: "path"
          description: "order"
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        "400":
          description: "Invalid ID supplied"
    post:
      tags:
        - "rooms"
      summary: "Add room"
      description: ""
      operationId: "addRoom"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRoomRequest'
        required: true
      #      consumes:
      #        - "application/x-www-form-urlencoded"
      #      produces:
      #        - "application/json"
      responses:
        '200':
          description: Room added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddRoomResponse'
        "405":
          description: "Invalid input"
  /rooms/{roomId}:
    delete:
      tags:
        - "rooms"
      summary: "Deletes room and its bookings"
      description: ""
      operationId: "deleteRoom"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "roomId"
          in: "path"
          description: "Room id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Room deleted"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Room not found"
  /bookings:
    get:
      tags:
        - "bookings"
      summary: "Return bookings by room ID"
      description: ""
      operationId: "getBookingsByRoomId"
      produces:
        - "application/json"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetBookingRequest'
        required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetBookingResponse"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Room not found"
    post:
      tags:
        - "bookings"
      summary: "Add booking"
      description: ""
      operationId: "addBooking"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddBookingRequest'
        required: true
      #      consumes:
      #        - "application/x-www-form-urlencoded"
      #      produces:
      #        - "application/json"
      responses:
        '200':
          description: Booking added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddBookingResponse'
        "405":
          description: "Invalid input"
  /bookings/{bookingId}:
    delete:
      tags:
        - "bookings"
      summary: "Deletes booking"
      description: ""
      operationId: "deleteBooking"
      produces:
        - "application/json"
      parameters:
        - name: "bookingId"
          in: "path"
          description: "Booking id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Booking deleted"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Booking not found"
components:
  schemas:
    GetBookingRequest:
      required:
        - room_id
      type: object
      properties:
        room_id:
          type: string
    GetBookingResponse:
      required:
        - booking_id
        - start_date
        - expiration_date
      type: object
      properties:
        booking_id:
          type: string
        start_date:
          type: string
        expiration_date:
          type: string

    AddBookingRequest:
      required:
        - room_id
        - start_date
        - expiration_date
      type: object
      properties:
        room_id:
          type: string
        start_date:
          type: string
        expiration_date:
          type: string
    AddBookingResponse:
      required:
        - booking_id
      type: object
      properties:
        booking_id:
          type: string

    AddRoomRequest:
      required:
        - price
        - desc
      type: object
      properties:
        price:
          type: string
        desc:
          type: string
    AddRoomResponse:
      required:
        - room_id
      type: object
      properties:
        room_id:
          type: string

    Room:
      required:
        - desc
        - price
        - date_added
      type: object
      properties:
        desc:
          type: string
        price:
          type: string
        date_added:
          type: string
